### PR TITLE
Completed MVP #2 features with layer limits, cleaned up sidebar, and other UI improvements

### PR DESCRIPTION
**Pull request by prashmalyala**
MVP #2 scope included deleting, updating, and creating OUs as well as basic filtering to limit the number of OUs displayed at a time - this was accomplished through layer limit rendering. Search feature implementation scoped for MVP #3.

### CODE REVIEW

**Review by phillipdold — COMMENTED** [review]
Like the UI a lot. Great job. Is search suppose to work for MVP #2?

**Comment by prashmalyala** [comment]
> Like the UI a lot. Great job. Is search suppose to work for MVP #2?

Awesome, thanks! And no, the MVP 2 focus is on basic filtering by layers; Search is the more advanced MVP 3 filtering feature (as it requires searching for an orgunit, managing potential duplicate names, and then tracing the path from the root to said orgunit).

**MVP 2 milestones**:
1. OU Visualization, Prashant
    a. Customer can create, delete, and update OUs
    b. Limit the amount of OUs that show up on screen, possibly limit the amount of work API is doing
        i. Use basic filtering to make it work (i.e. show the top N layers)

**Review by phillipdold — APPROVED** [review]
Okay. Normally, we shouldn't put the UI element in until it works and it's also not best practice to include commented out code as well (ie. var searchButton....)

Approving the changes

**Comment by prashmalyala** [comment]
> Okay. Normally, we shouldn't put the UI element in until it works and it's also not best practice to include commented out code as well (ie. var searchButton....)
> 
> Approving the changes

Yeah, that's a great point, I agree it doesn't make much sense to show the Search Bar in our presentation demo if it doesn't work yet. I removed the commented code as well as the Search Bar from the UI for the time being.

**Pull request merged**
